extends:
  - eslint:recommended
  - airbnb-base
env:
  es6: true
  browser: true
rules:
  # ペーストで済むようにJSONにとどめとこう
  no-unused-vars: 'warn'
  quotes: ['error', 'single']
  no-console: ['error', { allow: ['warn', 'error', 'log', 'dir'] }]
  comma-dangle: ['error', 'always-multiline']
  func-names: ['error', 'never']
  space-before-function-paren: ['error', 'never']
  wrap-iife: ['error', 'inside']
  no-param-reassign: ['error', { 'props': false }]
  guard-for-in: 0
  no-restricted-syntax: 0
  no-constant-condition: ['error', { 'checkLoops': false }]
  prefer-destructuring: 0
  symbol-description: 0
  yoda: [2, 'never', { 'exceptRange': true }]
  class-methods-use-this: 0
  max-len: ['warn', { 'code': 80 }]
  import/no-extraneous-dependencies:
    ['error', { devDependencies: true, optionalDependencies: false }]
